// prettier-ignore

/* eslint-disable no-template-curly-in-string */
/* eslint-disable max-lines */
export default {
  AuthenticationScreen: {
    authenticationDescription: "Authentifier vous pour continuer",
    setUp: "Configurer authentification biométrique",
    setUpAuthenticationDescription: "Utiliser l'authentification biométrique",
    skip: "Sauter cette étape",
    unlock: "Déverrouiller",
    usePin: "Utiliser un NIP",
  },
  BalanceHeader: {
    currentBalance: "Solde actuel",
    hiddenBalanceToolTip: "Appuyer pour révéler votre solde",
  },
  ContactsScreen: {
    noContactsTitle: "Aucun contact trouvé",
    noContactsYet: "Envoyer ou recever un paiement en utilisant un nom d'utilisateur et il sera automatiquement ajouté à vos contacts ici",
    noMatchingContacts: "Aucun contact ne correspond à votre recherche.",
    title: "Contacts",
  },
  ContactDetailsScreen: {
    title: "Transactions avec %{input}",
  },
  EarnScreen: {
    earnSats: {
      one: "Gagner 1 sat",
      other: "Gagner {{formatted_number}} sats",
    },
    earns: [
      {
        content: [
          {
            answers: [
              "Monnaie numérique",
              "Un jeu vidéo",
              "Un nouveau personne de dessins animés"
            ],
            feedback: [
              "Exact. Vous avez gagné 1 “sat”!",
              "Faux, svp essayer de nouveau.",
              "Vraiment pas. Au moins, aucun que l'on connait!",
            ],
            id: "whatIsBitcoin",
            question: "Qu'est-ce que le Bitcoin exactement?",
            text: "Le Bitcoin est une monnaie numérique. \n\n Deux personnes peuvent s'échanger un Bitcoin instantanément et en toute sécurité partout dans le monde, sans l'aide d'une banque ou d'autre compagnie financière.",
            title: "Qu'est-ce que le Bitcoin exactement?",
            type: "Text",
          },
          {
            answers: [
              "La plus petite unité de Bitcoin",
              "Un petit satellite",
              "Un chat spatial 🐱🚀",
            ],
            feedback: [
              "Exact. Vous vous méritez deux sats!!",
              "Peut-être… mais ce n'est pas la bonne réponse dans ce contexte 🙂",
              "Vraiment pas.... mais ce serait génial!",
            ],
            id: "sat",
            question: "Je viens de gagner un “Sat”, qu'est-ce que c'est?",
            text: "Un “Sat” est la plus petite unité d'un bitcoin. \n\n On sait tous qu'un dollard peut être diviser en 100 centimes. De façon similaire, un Bitcoin peut se diviser en 100,000,000 sats. \n\n En fait, on a pas besoin d'avoir tout un bitcoin pour s'en servir. On peut se servir de bitcoin que l'on possède 20 sats, 3000 sats ou 100,000,000 sats (ce qui équivaut à un bitcoin).",
            title: "Je viens de gagner un “Sat”, qu'est-ce que c'est?",
            type: "Text",
          },
          {
            answers: [
              "Dans le réseau Internet",
              "Sur la Lune",
              "Dans un compte en banque fédéral"
            ],
            feedback: [
              "Exact. Vous gagnez un autre 5 sats.",
              "Faux. Au moins pas pour l'instant ;)",
              "Faux, svp essayer de nouveau.",
            ],
            id: "whereBitcoinExist",
            question: "Où sont définis les bitcoins?",
            text: "Le Bitcoin est une nouvelle forme de monnaie. Tout le monde peuvent s'en servir, à n'importe quel moment et n'importe où dans le monde. \n\n Il n'est pas rattaché à un gouvernment ou une région spécifique (comme le dollard US par exemple). De plus, il n'y a pas de version sur papier, sur pièces métalliques ou de cartes de plastique. \n\n Tout est 100% numérique. Le Bitcoin est un réseau d'ordinateurs reliés par internet. \n\n Vos bitcoins sont facilement géré à partir de votre ordinateur ou de votre téléphone!",
            title: "Où sont définis les bitcoins?",
            type: "Text",
          },
          {
            answers: [
              "Une communauté mondiale d'utilisateurs volontaires",
              "Mr Burns de la série télévisée Les Simpson",
              "Le gouvernement de France",
            ],
            feedback: [
              "C'est la bonne réponse. Le Bitcoin est possible grâce à la participation de personnes exécutant le logiciel bitcoin sur leurs ordinateurs ou leurs téléphones.",
              "Une idée amusante, mais incorrecte!",
              "Faux. Aucun gouvernement ni aucune compagnie ne contrôle le Bitcoin.",
            ],
            id: "whoControlsBitcoin",
            question: "Qui contrôle le Bitcoin?",
            text: "Le Bitcoin n'est pas controlé pour une personne, une compagnie ou un gouvernement. \n\n Il est dirigé par la communauté d'utilisateurs, des gens et des compagnies d'un peu partout dans le monde, qui roulent logiciel bitcoin de façon volontaire sur leurs ordinateurs ou leurs téléphones.",
            title: "Qui contrôle le Bitcoin?",
            type: "Text",
          },
          {
            answers: [
              "Non, c'est impossible de copier ou dupliquer la valeur du bitcoin",
              "Oui, on peut copier des bitcoins aussi facilement que l'on peut copier des photos numériques",
              "Oui, mais copier des bitcoins nécessite des ordinateurs spécialisés",
            ],
            feedback: [
              "C'est tout à fait juste!",
              "Tu sais que ce n'est pas vrai. Essaie de nouveau.",
              "Faux. Il n'y a aucune façon de copier ou dupliquer des bitcoins.",
            ],
            id: "copyBitcoin",
            question: "Si le Bitcoin est une monnaie numérique, est-ce que quelqu'un pourrait le copier et ainsi créer de l'argent gratuit?",
            text: "La valeur d'un bitcoin ne peut jamais être copié. C'est justement pour cela que le Bitcoin est une invention aussi puissante!!\n\n La plupart des fichiers numériques, comme les photo d'un iPhone, une chanson en format MP3, ou un document Microsoft Word, peuvent facilement être dupliqués et partagés. \n\n Le logiciel Bitcoin empêche la duplication, ou dans le jargon bitcoin “la double dépense”, de la monnaie numérique. On va expliquer le fonctionnement précis de l'algorithme plus tard!",
            title: "Si le Bitcoin est une monnaie numérique, est-ce que quelqu'un pourrait le copier et ainsi créer de l'argent gratuit?",
            type: "Text",
          },
        ],
        meta: {
          id: "bitcoinWhatIsIt",
          title: "Bitcoin: Qu'est-ce que c'est?",
        },
      },
      {
        content: [
          {
            answers: [
              "Parce que les gens ont confiance que d'autres personnes vont évaluer la monnaie de façon similaire",
              "Parce que votre mère vous l'a dit",
              "Parce qu'un billet d'un dollar vaut son poids en or",
            ],
            feedback: [
              "Exact. C'est ce qui permet à la monnaie de fonctionner!",
              "Elle l'a peut être fait. Mais ce n'est pas la bonne réponse ici!",
              "Non, plus maintenant. Dans le passé, on pouvait échanger des dollars contre de l'or, mais ce n'est plus le cas.",
            ],
            id: "moneySocialAggrement",
            question: "Pourquoi les monnaies ont de la valeur?",
            text: "La monnaie nécessite la confiance du peuple.\n\n Les gens font confiance à la monnaie papier dans leurs poches. Ils font confiance aux chiffres dans leurs comptes banquaires en ligne. Ils font confiance que le solde de leurs cartes cadeaux sera disponible pour des transactions. \n\n Avoir de la monnaie permet au gens de l'échanger facilement pour des biens ou des services.",
            title: "L'argent est un contrat social.",
            type: "Text",
          },
          {
            answers: [
              "La double coïncidence des besoins",
              "La coïncidence du jour et de la nuit",
              "La coïncidence de la lune bloquant la lumière du Soleil",
            ],
            feedback: [
              "Exact. La monnaie permet des transactions qui ne nécessite par de négotiation sur la forme du paiement.",
              "Il ne faut pas cliquer sur n'importe quoi voyons...",
              "Et non, on appelle cette coïncidence une éclipse solaire 🌚 et la monnaie ne change rien dans ce cas.",
            ],
            id: "coincidenceOfWants",
            question: "Quelle coïncidence est évitée par l'utilisation de la monnaie?",
            text: "Il y a des siècles, avant l'invention de la monnaie, les gens faisaient du troc -- c'est-à-dire ils négotiaient l'échange d'un bien contre un autre type de bien ou de service. \n\n Disons que vous vouliez mangez dans un restaurant et que vous offriez au propriétaire un balais en échange d'un repas. Le propriétaire pouvait dire “non, mais je vais prendre trois chapeaux, si vous en avez”. \n\n Vous pouvez imaginer comme un système de troc pouvait être difficile et inefficace!\n\n En contrast, avec de la monnaie, un simple billet de 20$ règle cette transaction en sachant que le propriétaire du restaurant l'acceptera volontier.",
            title: "La monnaie permet d'éviter la “double coïncidence des besoins”...  C'est quoi ça??",
            type: "Text",
          },
          {
            answers: [
              "Des pierres, des coquillages et de l'or",
              "Des petites maisons de Monopoly en plastique",
              "Des pièces en chocolat",
            ],
            feedback: [
              "Exact. Des objets rares et difficiles à copier étaient souvent utilisés comme monnaie.",
              "Faux. Ils ont de la valeur lorsque l'on joue au jeu, mais pas dans le monde réel!",
              "Non. Ils sont délicieux, mais ils ne seraient pas utile comme monnaie.",
            ],
            id: "moneyEvolution",
            question: "Historiquement, quels objets ont déjà été utilisés comme monnaie?",
            text: "Thousands of years ago, society in Micronesia used very large and scarce stones as a form of agreed currency. \n\nStarting in the 1500’s, rare Cowrie shells (found in the ocean) became commonly used in many nations as a form of money.\n\nAnd for millenia, gold has been used as a form of money for countries around the world -- including the United States (until 1971).",
            title: "La monnaie a évoluée depuis le début de la civilisation.",
            type: "Text",
          },
          {
            answers: [
              "Parce qu'ils ont des caractéristiques essentielles, comme une bonne durabilité, une uniformité et qu'ils sont divisibles.",
              "Parce qu'ils brillent et qu'ils sont jolies.",
              "Parce qu'ils peuvent être transporter dans nos poches.",
            ],
            feedback: [
              "Exact. D'autres caractéristiques essentielles sont qu'ils sont rares et portables.",
              "Faux. C'est peut-être le cas, mais ce ne sont pas des caractéristiques utiles pour de la monnaie.",
              "Pas tout à fait. Bien que c'est objets étaient portable, ce n'est pas une raison suffisante en soi.",
            ],
            id: "whyStonesShellGold",
            question: "Pourquoi les pierres, les coquillages et l'or furent utilisés comme monnaie?",
            text: "Ces objets possèdent des caractéristiques essentielles, mais pas tous, pour une bonne monnaie. \n\n Quelles sont les caractéristiques essentielles pour une “bonne” monnaie? \n Rareté: peu abondante et difficile à reproduire ou copier \n Elle doit être acceptée: c'est relativement facile de vérifier son authenticité \n Durabilité: facile à maintenir, sans qu'elle périsse ou tombe en pièces \n Uniformité: facilement échangeable avec un autre objet du même type \n Portabilité: facile à transporter \n Divisible: peut-être séparer en pièces plus petites.",
            title: "Pourquoi les pierres, les coquillages et l'or furent utilisés comme monnaie?",
            type: "Text",
          },
          {
            answers: [
              "La monnaie permet d'acheter des biens et des services aujourd'hui et demain.",
              "La monnaie permet de se rendre sur la Lune.",
              "La monnaie est la solution de tous les problèmes.",
            ],
            feedback: [
              "C'est tout à fait cela!",
              "Faux. Bien que cela puisse changer dans le futur ;)",
              "Pas tout à fait. Bien que des gens le croient, cette réponse n'identifie pas la raison d'être principale de la monnaie.",
            ],
            id: "moneyIsImportant",
            question: "Quelle est la raison d'être principale de la monnaie? Pourquoi est-elle importante?",
            text: "Tout le monde sait que la monnaie est importante. \n\n La plupart des gens échangent leur temps et leur énergie, sous la forme de travail, pour obtenir de la monnaie. Ils le font pour pouvoir acheter des biens et des servies aujourd'hui et dans le futur.",
            title: "La monnaie est importante pour les individus",
            type: "Text",
          },
          {
            answers: [
              "La banque centrale du pays, par exemple la Banque Centrale des États-Unis (La Réserve Fédérale)",
              "Mr Burns de la série télévisée Les Simpson",
              "Un gars avec une imprimante dans son sous-sol",
            ],
            feedback: [
              "Exact. Le gouvernement peut imprimer autant de monnaie qu'il veut, quand il veut.",
              "Faux. Bien que dans la série, il ne manque presque jamais d'argent.",
              "Non. Certaines personnes peuvent imprimer des faux billets, mais ce n'est définitivement pas légal!",
            ],
            id: "moneyImportantGovernement",
            question: "Qui peut imprimer de la monnaie quand ils le veulent?",
            text: "Les économies modernes sont organisées par les nations: USA, Japon, Suisse, Brésil, Norvège, Chine, etc. \n\n Ainsi, dans la majorité des nations, le gouvernement détient le pouvoir de créer et de contrôler la monnaie. \n\n Aux États-Unis, la Banque Centrale (appelée la Réserve Fédérale, ou “Fed”) peut imprimer ou créer plus de Dollars US quand elle le désire. \n\n La “Fed” ne requière pas la permission du Président, ni du Congrès, et certainement pas des citoyens. \n\n Imaginez si vous pouviez imprimer des Dollars US quand vous le vouliez, que feriez-vous??",
            title: "La monnaie est aussi importante pour les gouvernements",
            type: "Text",
          },
        ],
        meta: {
          id: "WhatIsMoney",
          title: "Qu'est-ce que c'est de la monnaie? ",
        },
      },
      {
        content: [
          {
            answers: [
              "Elle est créée sous les ordres du gouvernement national du pays.",
              "Par le gérant d'une banque locale.",
              "Par le créateur du jeu Monopoly.",
            ],
            feedback: [
              "Exact. La banque centrale d'un gouvernement crée la monnaie fiat.",
              "Faux. Une banque locale ne peut que gérer de la monnaie qui a été créée précédemment par le gouvernement.",
              "Non. Essayez encore!",
            ],
            id: "WhatIsFiat",
            question: "Qui crée l'argent fiat, comme le Dollar US ou Canadien?",
            text: "Toutes les monnaies nationales en circulation aujourd'hui sont appelées monnaie fiat. Ceci inclus le Dollars US, le Yen Japonais, le Franc Suisse, le Dollar Canadien et ainsi de suite. \n\n Le mot “fiat” provient du Latin, il signifie “par décret”, c'est-à-dire “par ordre officielle”. \n\n Ceci signifie que toute monnaie fiat, incluant le Dollar US, est simplement créée sous les ordres du gouvernement national.",
            title: "La monnaie fiat: qu'est-ce que c'est?",
            type: "Text",
          },
          {
            answers: [
              "Tous les gouvernements abusent éventuellement de leur pouvoir sur leurs monnaies fiat.",
              "Les banques locales peuvent manquer d'espace dans leur coffres pour stoquer tous les billets.",
              "On pourrait manquer d'arbres pour fabriquer tous ces billets en papier additionnels.",
            ],
            feedback: [
              "Exact. Historiquement, les gouvernements n'ont pas pu résister à la tentation d'imprimer plus de monnaie puisqu'ils n'ont pas d'obligation de repayer cette nouvelle monnaie.",
              "Non, c'est certainement pas le cas.",
              "Faux. D'ailleur plusieurs billets ne sont pas fait à partir des arbres. Essayez encore.",
            ],
            id: "whyCareAboutFiatMoney",
            question: "Pourquoi devrais-je me soucier du contrôle du gouvernement sur la monnaie fiat?",
            text: "Tel que vu dans un quiz précédent, la banque centrale des États-Unis est la Réserve Fédérale, ou la “Fed”.\n\n La Fed peut imprimer plus de monnaie quand elle le désire et elle ne requiert pas la permission du Président, ni du Congrès et certainement pas des citoyens. \n\n Avec ce genre de contrôle sur la monnaie, il peut être très tentant pour ces authorités d'en abuser. Cela mène parfois à de l'inflation massive, des confiscations arbitraires et de la corruption. \n\n En fait, Alan Greenspan, le célèbre ex-président de la The Fed, a déclaré que les États-Unis “peut payer n'importe quelle dette, puisque l'on peut toujours imprimer plus de billets pour faire cela”.",
            title: "Je fais confiance à mon gouvernement. \n Pourquoi je devrais me soucier de la monnaie fiat?",
            type: "Text",
          },
          {
            answers: [
              "La création de monnaie supplémentaire cause de l'inflation.",
              "Les gens doivent échanger leur anciens billets de bank à chaque année.",
              "L'apparence des billets change.",
            ],
            feedback: [
              "Exact. Ceci signifie que les biens et les services vont être plus dispendieux à l'avenir.",
              "Non. Les vieux billets sont aussi valides que les nouveaux.",
              "Faux. Bien que le gouvernement peut change l'apparence des billets, ceci n'a rien à voir avec l'accroissement des réserves monétaires.",
            ],
            id: "GovernementCanPrintMoney",
            question: "Quel impact aura l'impression de monnaie par le gouvernement?",
            text: "Tout le monde devrait s'en soucier! \n\n L'impression de monnaie par le gouvernement, ou plutôt l'accroissement de la réserve monétaire, cause de l'inflation. \n\n L'inflation est un accroissement du prix des biens et des services. En d'autre mots, le prix d'un objet sera plus dispendieux à l'avenir que maintenant. \n\n Alors que signifie l'inflation pour les citoyens? \n\n Au Royaume-Uni, la Livre Sterling  a perdu 99.5% de sa valeur depuis sont introduction il y a plus de 300 ans. \n\n Aux Etats-Unis, le dollar a perdu 97% de sa valeur depuis la fin de la Deuxième Guerre Mondiale, il y a environ 100 ans. \n\n Cela signifie qu'un bifteck qui coûtait $0.30 en 1920... était $3 en 1990… et est environ $15 aujourd'hui, en l'an 2020!",
            title: "Qui devrait se soucier que le gouvernement peut imprimer de la monnaie sans limite?",
            type: "Text",
          },
          {
            answers: [
              "Toutes les monnaies fiat ont perdu une quantité massive de valeur.",
              "La valeur reste la même pour toujours.",
              "L'apparence et la forme des billets papier change à tous les 10 ans environ.",
            ],
            feedback: [
              "Exact. Ceci est vrai même pour le USD, qui a perdu 97% de sa valeur dans le dernier 100 ans.",
              "Faux. Essayez de nouveau.",
              "Pas tout à fait. Bien que l'apparence et la forme des billets peuvent changer, ceci n'a aucun impacte sur leur valeur.",
            ],
            id: "FiatLosesValueOverTime",
            question: "Qu'arrive-t-il à la valeur des monnaies fiat avec le temps?",
            text: "C'est le cas. \n\n A travers l'histoire, il y a eu 775 monnaies fiat qui ont été créées. La plupart n'existe plus et l'espérance de vie d'une nouvelle monnaie fiat est de seulement 27 ans. \n\n La livre Sterling est la plus vieille monnaie fiat du monde. Elle a perdu plus de 99% de sa valeur depuis 1694. \n\n Il n'y a aucun exemple de monnaie fiat ayant conservé sa valeur. Ceci est l'inflation. \n C'Est une forme de vol de votre argent durement gagner!",
            title: "Est-ce que cela signifie que toutes les monnaies fiat perdent de la valeur avec le temps?",
            type: "Text",
          },
          {
            answers: [
              "La monnaie est difficile a bouger autour du monde et elle peut être surveillée.",
              "On a plus besoin de monnaie au 21ième siècle.",
              "L'argent est la source de tous les maux.",
            ],
            feedback: [
              "Exact. On va expliquer plus de détails concernant ces enjeux dans un prochain quiz. Continuez de creuser!!",
              "Faux. Vous savez que ce n'est pas la cas.",
              "Bien que plusieurs personnes peuvent y croire, ce n'est pas la réponse que l'on cherche.",
            ],
            id: "OtherIssues",
            question: "Quels autres enjeux est associés avec les monnaies fiat?",
            text: "Oui, il y a plusieurs autres enjeux avec les monnaies fiat modernes. \n\n Premièrement, il peut être extrêmement difficile de déplacer de la monnaie dans le monde. Souvent, les gouvernements vont mettre des restrictions sur ces déplacements, et parfois, ils vont même confisquer les fonds sans justifications valides. Même quand on réussit a envoyer de l'argent, des frais de transaction énormes rendent le déplacement dispendieux. \n\n Deuxièmement, même aux États-Unis, il y a eu une perte totale de discrétion puisque la majorité du commerce utilise des carte de débit ou de crédit, ainsi que des systèmes en ligne tel que PayPal et Apple Pay.\n\n Avez-vous remarqué que des publicités apparaissent sur vos média sociaux ou dans vos courriels quelques instants après que vous ayez fait une recherche sur un bien ou un service? On appelle ceci “l'économie de la surveillance”, et c'est basé sur la vente de vos données financières.",
            title: "D'accord, les monnaie fiat perdent de la valeur avec le temps. Y-a-t-il d'autres problèmes?",
            type: "Text",
          },
        ],
        meta: {
          id: "HowDoesMoneyWork",
          title: "Comment fonctionne la monnaie? ",
        },
      },
      {
        content: [
          {
            answers: [
              "Oui. On ne pourra jamais créer plus de 21 millions de bitcoins.",
              "Non. Le gouvernement peut créer plus de bitcoin quand il le veut.",
              "Non, le logiciel bitcoin peut être changé pour permettre la création de plus de bitcoins.",
            ],
            feedback: [
              "Exacte. En limitant la quantité qui peut être créée, le Bitcoin a été conçu pour accroître sa valeur avec le temps.",
              "Faux. Le gouvernement n'a aucun contrôle sur le Bitcoin.",
              "Faux. Une des caractéristiques clées du bitcoin est que la réserve est limitée pour toujours.",
            ],
            id: "LimitedSupply",
            question: "Est-ce que la réserve de bitcoin limitée pour toujours?",
            text: "Les gouvernement peuvent imprimer de la monnaie fiat en quantités illimitées. \n\n Contrairement à cela, la réserve maximale de Bitcoin est fixée et elle ne peut jamais dépasser 21 millions de bitcoins. \n\n Un accroissement continuel de la réserve de monnaie fiat cause de l'inflation. Ceci signifie que l'argent que vous avez aujourd'hui aura une valeur moindre dans le futur. \n\n Un exemple simple de ceci: \n Une miche de pain qui valait environ 8 cents en 1920, valait environ $1.00 en 1990 et aujourd'hui il vaut environ $2.50 ! \n\n La réserve limitée de bitcoin a l'effet inverse, une de déflation. \n\n Ceci signifie que le bitcoin que vous détenez aujourd'hui est conçu pour avoir plus de valeur dans le futur, parce qu'il est rare.",
            title: "Caractéristique spéciale #1:\n Une réserve limitée",
            type: "Text",
          },
          {
            answers: [
              "Non.  Le Bitcoin est complètement “décentralisé”.",
              "Oui. Il est contrôlé par les Nations Unis.",
              "Oui. Il est contrôlé par les plus grandes banques du monde.",
            ],
            feedback: [
              "Exact. Il n'y a pas de compagnie, de gouvernement ou d'institution qui contrôle le bitcoin. N'importe qui peut utiliser le bitcoin et tout ce qu'il faut c'est un téléphone intelligent et une connection à internet.",
              "Faux. Essayez de nouveau.",
              "Faux, mais vous le saviez déjà!",
            ],
            id: "Decentralized",
            question: "Est-ce que le bitcoin est centralisé?",
            text: "La monnaie fiat est contrôlée par les banques et les gouvernements, c'est pour cela que l'on dit qu'elle est centralisée. \n\n Le Bitcoin n'est pas contrôlé par une personne, un gouvernement ou une compagnie, se qui signifie qu'il est décentralisé. \n\n Puisque personne ne contrôle le bitcoin, cela signifie que personne ne peut vous limiter son accès, pour des raisons de race, de genre, de votre revenu, de votre cote de crédit, votre position géographique ou n'importe quel autre facteur. \n\n N'importe qui, n'importe ou dans le monde, peut accéder et utiliser le Bitcoin quand il le veut. Tout ce qui est nécessaire est un ordinateur ou un téléphone intelligent et une connection internet!",
            title: "Caracteristique spéciale #2: Décentralisation",
            type: "Text",
          },
          {
            answers: [
              "Non. Il est impossible de faire des contrefaçons de Bitcoin.",
              "Oui. Sauf que la création de faux bitcoin nécessite des ordinateurs très spécialisés.",
              "Oui. Le gouvernement peut imprimer autant de bitcoins qu'il le souhaite.",
            ],
            feedback: [
              "Ceci est la bonne réponse. Dans un prochain quiz, “Honey Badger” vous expliquera pourquoi c'est ainsi!",
              "Faux. Il n'y a aucune façon de copier ou dupliquer la valeur du bitcoin.",
              "Faux. Bien que le gouvernement peut imprimer une quantité illimité de dollars, il ne peut pas imprimer de bitcoin.",
            ],
            id: "NoCounterfeitMoney",
            question: "Est-ce que l'on peut créer des contrefaçons de Bitcoin?",
            text: "La monnaie papier, les chèques et les transactions par carte de crédit peuvent tous être contrefait ou frauduleux. \n\n Le logiciel unique sur lequel repose le réseau Bitcoin élimine toute possibilité de duplication, y compris pour faire des contrefaçons. \n\n Les nouveaux bitcoin peuvent seulement être créé s'il y a un consensus parmis les participants du réseau, c'est-à-dire les gens qui roulent le logiciel bitcoin sur leurs ordinateurs ou téléphone intelligent. \n\n Ceci rend impossible la création de contrefaçons ou de faux bitcoins.",
            title: "Caractéristique spéciale #3: \nPas de contrefaçon",
            type: "Text",
          },
          {
            answers: [
              "0.00000001 BTC",
              "Un bitcoin entier. Il est impossible d'utiliser moins de un bitcoin.",
              "0.01 BTC",
            ],
            feedback: [
              "Oui. On peut diviser un bitcoin en 100 000 000 d'unités. Comme mentionné, la plus petite unité d'un bitcoin - B0.00000001 - s'appelle un “sat”",
              "Faux. Un bitcoin est très divisible. On peut facilement utiliser une très petite fraction de bitcoin",
              "Incorrect. Quoique la plus petite unité du dollar US est un cent, un bitcoin est divisible par un facteur de plus de 100x.",
            ],
            id: "HighlyDivisible",
            question: "Quelle est la plus petite fraction de bitcoin qu'une personne peut posséder, ou utiliser?",
            text: "La monnaie fiat désuette peut seulement être dépensée en montants multiples de un cent - c'est-à-dire deux décimales pour un dollar CAD ($0.01).\n\n d'autre part, un bitcoin peut être divisé en 100 000 000 d'unités. Cela signifie qu'il est possible de dépenser aussi peu que ₿0.00000001. Notez le symbole \"₿\" utilisé, qui est l\'équivalent Bitcoin du \"$\". Vous verrez parfois l'utilisation de \"BTC\", au lieu du ₿. \n\nPar contraste, Bitcoin permet de très petits paiements - aussi peu que un cent CAD",
            title: "Caractéristique Spéciale #4: \nHautement Divisible",
            type: "Text",
          },
          {
            answers: [
              "Oui. Le réseau Bitcoin est extrêmement sécuritaire",
              "Peut-être. Cela dépends du jour de la semaine.",
              "Non. bitcoin est un logiciel libre et est facilement attaquable.",
            ],
            feedback: [
              "Correct. Dans les faits, le réseau bitcoin n'a jamais été attaqué. Répondez à la prochain question pour en apprendre plus!",
              "Bel essai, mais faux. Le réseau bitcoin est sûr et sécuritaire - 24 heures par jour, 365 jours par année.",
              "Icorrect. Quoique bitcoin est en effet un \"logiciel libre\" - c'est-à-dire disponible au public gratuitement - il est extrêmement sécure.",
            ],
            id: "securePartOne",
            question: "Is the Bitcoin network secure?",
            text: "The bitcoin network is worth well over $100 billion today. Accordingly, the network must be very secure — so that money is never stolen. \n\nBitcoin is known as the world’s first cryptocurrency. \n\nThe “crypto” part of the name comes from cryptography. Simply put, cryptography protects information through very complex math functions. \n\nMost people do not realize — but Bitcoin is actually the most secure computer network in the world ! \n\n(you may have heard about bitcoin “hacks” — which we will debunk in the next quiz)",
            title: "Caractéristique Spéciale #5: \nSécurité -- Partie I",
            type: "Text",
          },
          {
            answers: [
              "Non. Bitcoin n'a jamais été hacké",
              "Oui. Bitcoin se fait hacké régulièrement.",
              "Oui. Bitcoin se fait hacké habituellement la fin de semaine lorsque les banques traditionnelles sont fermées.",
            ],
            feedback: [
              "Correct. Le réseau Bitcoin n'a jamais été compromis. Cependant, il est important d'utiliser des portefeuilles numériques sécuritaires en tout temps pour conserver de façon sécuritaire vos propres bitcoin.",
              "Faux. Essayez encore.",
              "Pas bête, vous savez que ce n'est pas la bonne réponse.",
            ],
            id: "securePartTwo",
            question: "Est-ce que Bitcoin a déjà été hacké?",
            text: "Pour être direct: le réseau Bitcoin lui-même n'a jamais été attaqué., Ne serait-ce qu'une seulle fois.\n\nAlors, qu'est-ce qui été attaqué exactement? \n\nCertains portefeuilles numériques qui n'avaient pas de système sécuritaire adéquat. \n\nDe la même façon qu'un portefeuille physique contient de la monnaie fiat (sous la forme de billets de banque), les portefeuilles numériques contiennent un certain montant en bitcoin.\n\nDans le monde physique, les criminels attaquent des banques - et s'enfuient avec des dollars sous forme de billets de banque. Le fait que certaines personnes volents des banques n'a aucun lien quant à savoir si le dollar CAD est une monnaie stable ou fiable. De la même façon, certains hackers ont volé des bitcoins dans des portefeuilles numériques non sécures - l'équivalent en ligne d'un vol de banque. \n\nCependant, il est important de savoir que le réseau Bitcoin n'a jamais été hacké ou compromis !",
            title: "Caractéristique Spéciale #5: \nSécurité -- Partie II",
            type: "Text",
          },
        ],
        meta: {
          id: "BitcoinWhySpecial",
          title: "Bitcoin: Pourquoi est-ce spécial? ",
        },
      },
    ],
    finishText: "C'est tout pour l'instant, nous vous laisserons savoir quand il y aura plus à découvrir.",
    getRewardNow: "Répondez au quiz",
    keepDigging: "Continuez à chercher!",
    phoneNumberNeeded: "Numéro de téléphone requis",
    quizComplete: "Quiz complété et {{amount}} sats gagnés",
    reviewQuiz: "Révisez le quiz",
    satAccumulated: "Sats accumulés",
    satsEarned: {
      one: "1 sat gagné",
      other: "{{formatted_number}} sats gagnés",
    },
    sectionsCompleted: "Vous avez terminé",
    title: "Gain",
    unlockQuestion: "Pour débloquer, répondwez à la question:",
    youEarned: "Vous avez gagné",
  },
  GetStartedScreen: {
    getStarted: "Commencez",
    headline: "Portefeuille développé par Galoy",
  },
  MapScreen: {
    locationPermissionMessage: "Entrez votre localisation, vous pourrez ainsi être inscrit sur la carte",
    locationPermissionNegative: "Annuler",
    locationPermissionNeutral: "Demandez vous plus tard",
    locationPermissionPositive: "OK",
    locationPermissionTitle: "Localisez votre position sur la carte",
    payBusiness: "payez l'entreprise",
    title: "Carte",
  },
  ModalClipboard: {
    dismiss: "Rejeter",
    open: "Ouvert",
    pendingBitcoin: "Vous avez une adresse Bitcoin address dans votre presse-papier",
    pendingInvoice: "Vous avez un Facture Lightning dans votre presse-papier",
  },
  MoveMoneyScreen: {
    receive: "Recevoir",
    send: "Envoyer",
    title: "Accueil",
    updateAvailable: "Une mise-à-jour est disponible.\nAppuyez sur tab pour lancer la mise-à-jour maintenant",
    useLightning: "Nous utilisons Lightning Network.",
  },
  Overlay: {
    accounts: "Commencez par obtenir\nquelques récompenses!",
    rewards: {
      download: "Nous vous donnons 1 sat comme cadeau\npour télécharger l'application.",
      getMore: "Apprenez à propos de #bitcoin et gagnez plus!",
    },
  },
  PinScreen: {
    attemptsRemaining: "NIP Incorrect. %{attemptsRemaining} tentatives restantes.",
    oneAttemptRemaining: "NIP Incorrect. 1 tentative restante.",
    setPin: "Définissez votre code NIP",
    setPinFailedMatch: "Les NIP ne correspondent pas - Définissez votre code NIP",
    storePinFailed: "Impossible d'enregistrer votre NIP.",
    tooManyAttempts: "Trop de tentatives échouées. Déconnection.",
    verifyPin: "Vérifiez votre code NIP",
  },
  PriceScreen: {
    oneDay: "1D",
    oneMonth: "1M",
    oneWeek: "1W",
    oneYear: "1Y",
    prevMonths: "Mois précédent",
    satPrice: "Prix pour 100,000 sats: ",
    thisMonth: "Mois courant",
    thisWeek: "Semaine courante",
    thisYear: "Année courante",
    today: "Aujourd'hui",
    yesterday: "Hier",
  },
  PrimaryScreen: {
    title: "Accueil",
  },
  ReceiveBitcoinScreen: {
    activateNotifications: "Voulez-vous activer les notifications pour être notifié lors de la réception de nouveaux paiements?",
    copyClipboard: "La Facture a été copiée dans le presse-papier",
    copyClipboardBitcoin: "L'adresse Bitcoin a été copiée dans le presse-papier",
    invoicePaid: "Cette Facture a été payée",
    setNote: "Ajoutez une note",
    tapQrCodeCopy: "Appuyez sur le code QR pour copier",
    title: "Recevez des Bitcoins",
    error: "Impossible de générer une Facture. SVP contactez le support technique.",
    copyInvoice: "Copiez la Facture",
    shareInvoice: "Partagez la Facture",
    addAmount: "Demandez un montant spécifique"
  },
  ScanningQRCodeScreen: {
    invalidContent: "Nous avons trouvé:\n\n{{found}}\n\nCeci n'est pas une adresse valide pour une Facture Lightning.",
    invalidTitle: "Code QR invalide",
    noQrCode: "Nous n'avons pas trouvé de Code QR dans l'image",
    title: "Scannez le Code QR",
    invalidContentLnurl: "Nous avons trouvé:\n\n{{found}}\n\n n'est pas supporté",
  },
  SecurityScreen: {
    biometricDescription: "Débloquez la reconnaissance faciale ou digitale.",
    biometricSubtitle: "Autorizez l'autentification biometrique",
    biometricTitle: "Biométrique",
    biometryNotAvailable: "Le senseur Biométrique n'est pas disponible.",
    biometryNotEnrolled: "SVP enregistrez au moins un senseur biométrique pour utiliser l'autentification biométrique.",
    hideBalanceDescription: "Masquez votre solde sur l'écran d'accueil par défaut, vous dissimuler vos informations à quiconque regarderait votre écran.",
    hideBalanceSubtitle: "Masquez le solde",
    hideBalanceTitle: "Solde",
    pinDescription: "Le NIP est utilisé comme méthode de sauvegarde pour l'authentification biométrique.",
    pinSubtitle: "Activer le code NIP",
    pinTitle: "Code NIP",
    setPin: "Définir le NIP",
  },
  SendBitcoinConfirmationScreen: {
    amountLabel: "Montant:",
    confirmPayment: "Confirmez le paiement",
    confirmPaymentQuestion: "Voulez-vous confiermer la paiement?",
    destinationLabel: "À:",
    feeLabel: "Frais",
    memoLabel: "Note:",
    paymentFinal: "Les paiements sont définitifs.",
    stalePrice: "Votre prix pour un bitcoin est ancien et a été mis-à-jour il y a {{timePeriod}}. Veuillez redémarrer l'application avant d'effectuer un paiement.",
    title: "Confirmez le paiement",
    totalLabel: "Solde:",
    totalExceed: "Le total excède votre solde de {{balance}}",
  },
  SendBitcoinScreen: {
    amount: "Montant",
    amountExceed: "Le montant excède votre solde de {{balance}}",
    amountIsRequired: "Un montant est requis",
    cost: "Coût",
    destination: "Destination",
    destinationIsRequired: "Une destination est requise",
    fee: "frais de réseau",
    feeCalculationUnsuccessful: "Calcul infructueux ⚠️",
    input: "nom usager, adresse Lightning ou BTC",
    invalidUsername: "npm usager invalide",
    noAmount: "Cette Facture ne contient pas de montant, vous devez indiquer manuellement quel montant vous désirez envoyer",
    notConfirmed: "Le paiement a été envoyé\nmais n'est pas encore confirmé\n\nVous pouvez vérifier l'état du paiement dans Transactions",
    note: "note optionnelle",
    success: "Le paiement a été envoyé avec succès",
    title: "Envoyer des bitcoins",
    usernameNotFound: "Un usager correspondant au nom saisi est introuvable.",
  },
  SettingsScreen: {
    activated: "Activé",
    tapLogIn: "Appuyez pour vous connecter",
    tapUserName: "Appuyez pour définir le nom d'usager",
    title: "Configurations",
    csvTransactionsError: "Impossible d'exporter les transactions vers csv. Quelque chose s'est mal passé. Si le problème persiste, veuillez contacter le support technique.",
    lnurlNoUsername: "To generate an lnurl address you must first set a username.  Do you want to set a username now?",
    copyClipboardLnurl: "L'adresse a été copiée dans le presse-papiers",
  },
  Languages: {
    "DEFAULT": "Default (OS)",
    "en": "English",
    "en-US": "English",
    "es": "Spanish",
    "es-SV": "Spanish",
    "pt-BR": "Portuguese",
    "fr-ca": "Français Canada"
  },
  SplashScreen: {
    update: "Votre application n'est plus à jour. Une mise à jour est nécessaire avant que l'application puisse être utilisée.\n\nCela peut être fait depuis le PlayStore pour Android et Testflight pour iOS",
  },
  TransactionDetailScreen: {
    detail: "Détails de la Transaction",
    paid: "Payé à/de",
    received: "Vous avez reçu",
    spent: "Vous avez dépensé",
  },
  TransactionScreen: {
    noTransaction: "Aucune transaction à afficher",
    title: "Transactions",
    transactionHistoryTitle: "Historique des transactions",
  },
  TransferScreen: {
    title: "Transfert",
    percentageToConvert: "% à convertir",
  },
  UsernameScreen: {
    "3CharactersMinimum": "at least 3 characters are necessary",
    "50CharactersMaximum": "Username cannot be longer than 50 characters",
    "available": "✅  %{input} is available",
    "confirmSubtext": "The username is permanent and can not be changed later",
    "confirmTitle": "Set %{input} as your username?",
    "forbiddenStart": "Cannot start with lnbc1, bc1, 1, or 3 and cannot be a Bitcoin address or Lightning invoice",
    "letterAndNumber": "Only lowercase letter, number and underscore (_) are accepted",
    "emailAddress": "Username must not be email address",
    "notAvailable": "❌  %{input} is not available",
    "success": "%{input} is now your username!",
    "usernameToUse": "What username do you want to use?",
  },
  WelcomeFirstScreen: {
    bank: "Bitcoin is designed to let you store, send and receive money, without relying on a bank or credit card.",
    before: "Before Bitcoin, people had to rely on banks or credit card providers, to spend, send and receive money.",
    care: "Why should I care?",
    learn: "I don't mean to badger you, but there's lot more to learn, dig in...",
    learnToEarn: "Learn to Earn",
  },
  WelcomePhoneInputScreen: {
    header: "Enter your phone number, and we'll text you an access code.",
    headerVerify: "Verify you are human",
    placeholder: "Phone Number",
    verify: "Click to Verify",
    continue: "Continue",
  },
  WelcomePhoneValidationScreen: {
    errorLoggingIn: "Error logging in. Did you use the right code?",
    header: "To confirm your phone number, enter the code we just sent you on %{phone}",
    need6Digits: "The code needs to have 6 digits",
    placeholder: "6 Digit Code",
    sendAgain: "Send Again",
  },
  common: {
    activateWallet: "Activate Wallet",
    amountRequired: "Amount is required",
    back: "Back",
    bank: "Bank",
    bankAccount: "Cash Account",
    bitcoin: "Bitcoin",
    bitcoinPrice: "Bitcoin Price",
    cancel: "Cancel",
    close: "Close",
    confirm: "Confirm",
    csvExport: "Export transactions as CSV",
    date: "Date",
    description: "Description",
    domain: "Domain",
    email: "Email",
    error: "Error",
    fatal: "Fatal",
    fee: "fee",
    Fee: "Fee",
    fees: "Fees",
    feeSats: "Fees (sats)",
    feesUsd: "Fees (USD)",
    firstName: "First Name",
    from: "From",
    hour: "hour",
    hours: "hours",
    invoice: "Invoice",
    language: "Language",
    languagePreference: "Language preference",
    lastName: "Last Name",
    later: "Later",
    loggedOut: "You have been logged out.",
    logout: "Log Out",
    minutes: "minutes",
    needWallet: "Validate your phone to open your wallet",
    next: "Next",
    No: "No",
    note: "Note",
    notification: "Notification",
    ok: "OK",
    openWallet: "Open Wallet",
    phoneNumber: "Phone Number",
    reauth: "Your session has expired. Please log in again.",
    restart: "Restart",
    sats: "sats",
    search: "Search",
    security: "Security",
    send: "Send",
    setAnAmount: "set an amount",
    share: "Share",
    shareBitcoin: "Share Bitcoin Address",
    shareLightning: "Share Lightning Invoice",
    soon: "Coming soon!",
    success: "Success!",
    to: "To",
    Total: "Total",
    transactions: "Transactions",
    transactionsError: "Error loading transactions",
    tryAgain: "Try Again",
    type: "Type",
    username: "Username",
    usernameRequired: "Username is required",
    yes: "Yes",
  },
  errors: {
    generic: "There was an error.\nPlease try again later.",
    invalidEmail: "Invalid email",
    invalidPhoneNumber: "is not a valid phone number",
    tooManyRequestsPhoneCode: "Too many requests. Please wait before requesting another text message.",
    network: {
      server: "Server Error. Please try again later",
      request: "Request issue.\nContact support if the problem persists",
      connection: "Connection issue.\nVerify your internet connection",
    },
    unexpectedError: "Unexpected error occurred",
    restartApp: "Please restart the application.",
    problemPersists: "If problem persists contact support.",
    fatalError: "Sorry we appear to be having issues loading the application data.  If problems persist please contact support.",
    showError: "Show Error",
  },
  notifications: {
    payment: {
      body: "You just received ${{value}} sats",
      title: "Payment received",
    },
  },
  tippingLink: {
    title: "Want to receive tips? Share your tipping link!",
    copied: "{{data}} saved to clipboard",
  },
  whatsapp: {
    contactUs: "Need help? Talk to us on WhatsApp!",
    defaultSupportMessage: "Hey there! I need some help with Bitcoin Beach Wallet",
    contactSupport: "Contact Support",
  },
  lnurl: {
    overLimit: "You can't send more than max amount",
    underLimit: "You can't send less than min amount",
    commentRequired: "Comment required",
    viewPrintable: "View Printable Version",
  },
}
