// prettier-ignore

/* eslint-disable no-template-curly-in-string */
/* eslint-disable max-lines */
export default {
  AuthenticationScreen: {
    authenticationDescription: "Authentifier vous pour continuer",
    setUp: "Configurer authentification biométrique",
    setUpAuthenticationDescription: "Utiliser l'authentification biométrique",
    skip: "Sauter cette étape",
    unlock: "Déverrouiller",
    usePin: "Utiliser un NIP",
  },
  BalanceHeader: {
    currentBalance: "Solde actuel",
    hiddenBalanceToolTip: "Appuyer pour révéler votre solde",
  },
  ContactsScreen: {
    noContactsTitle: "Aucun contact trouvé",
    noContactsYet: "Envoyer ou recever un paiement en utilisant un nom d'utilisateur et il sera automatiquement ajouté à vos contacts ici",
    noMatchingContacts: "Aucun contact ne correspond à votre recherche.",
    title: "Contacts",
  },
  ContactDetailsScreen: {
    title: "Transactions avec %{input}",
  },
  EarnScreen: {
    earnSats: {
      one: "Gagner 1 sat",
      other: "Gagner {{formatted_number}} sats",
    },
    earns: [
      {
        content: [
          {
            answers: [
              "Monnaie numérique",
              "Un jeu vidéo",
              "Un nouveau personne de dessins animés"
            ],
            feedback: [
              "Exact. Vous avez gagné 1 “sat”!",
              "Faux, svp essayer de nouveau.",
              "Vraiment pas. Au moins, aucun que l'on connait!",
            ],
            id: "whatIsBitcoin",
            question: "Qu'est-ce que le Bitcoin exactement?",
            text: "Le Bitcoin est une monnaie numérique. \n\n Deux personnes peuvent s'échanger un Bitcoin instantanément et en toute sécurité partout dans le monde, sans l'aide d'une banque ou d'autre compagnie financière.",
            title: "Qu'est-ce que le Bitcoin exactement?",
            type: "Text",
          },
          {
            answers: [
              "La plus petite unité de Bitcoin",
              "Un petit satellite",
              "Un chat spatial 🐱🚀",
            ],
            feedback: [
              "Exact. Vous vous méritez deux sats!!",
              "Peut-être… mais ce n'est pas la bonne réponse dans ce contexte 🙂",
              "Vraiment pas.... mais ce serait génial!",
            ],
            id: "sat",
            question: "Je viens de gagner un “Sat”, qu'est-ce que c'est?",
            text: "Un “Sat” est la plus petite unité d'un bitcoin. \n\n On sait tous qu'un dollard peut être diviser en 100 centimes. De façon similaire, un Bitcoin peut se diviser en 100,000,000 sats. \n\n En fait, on a pas besoin d'avoir tout un bitcoin pour s'en servir. On peut se servir de bitcoin que l'on possède 20 sats, 3000 sats ou 100,000,000 sats (ce qui équivaut à un bitcoin).",
            title: "Je viens de gagner un “Sat”, qu'est-ce que c'est?",
            type: "Text",
          },
          {
            answers: [
              "Dans le réseau Internet",
              "Sur la Lune",
              "Dans un compte en banque fédéral"
            ],
            feedback: [
              "Exact. Vous gagnez un autre 5 sats.",
              "Faux. Au moins pas pour l'instant ;)",
              "Faux, svp essayer de nouveau.",
            ],
            id: "whereBitcoinExist",
            question: "Où sont définis les bitcoins?",
            text: "Le Bitcoin est une nouvelle forme de monnaie. Tout le monde peuvent s'en servir, à n'importe quel moment et n'importe où dans le monde. \n\n Il n'est pas rattaché à un gouvernment ou une région spécifique (comme le dollard US par exemple). De plus, il n'y a pas de version sur papier, sur pièces métalliques ou de cartes de plastique. \n\n Tout est 100% numérique. Le Bitcoin est un réseau d'ordinateurs reliés par internet. \n\n Vos bitcoins sont facilement géré à partir de votre ordinateur ou de votre téléphone!",
            title: "Où sont définis les bitcoins?",
            type: "Text",
          },
          {
            answers: [
              "Une communauté mondiale d'utilisateurs volontaires",
              "Mr Burns de la série télévisée Les Simpson",
              "Le gouvernement de France",
            ],
            feedback: [
              "C'est la bonne réponse. Le Bitcoin est possible grâce à la participation de personnes exécutant le logiciel bitcoin sur leurs ordinateurs ou leurs téléphones.",
              "Une idée amusante, mais incorrecte!",
              "Faux. Aucun gouvernement ni aucune compagnie ne contrôle le Bitcoin.",
            ],
            id: "whoControlsBitcoin",
            question: "Qui contrôle le Bitcoin?",
            text: "Le Bitcoin n'est pas controlé pour une personne, une compagnie ou un gouvernement. \n\n Il est dirigé par la communauté d'utilisateurs, des gens et des compagnies d'un peu partout dans le monde, qui roulent logiciel bitcoin de façon volontaire sur leurs ordinateurs ou leurs téléphones.",
            title: "Qui contrôle le Bitcoin?",
            type: "Text",
          },
          {
            answers: [
              "Non, c'est impossible de copier ou dupliquer la valeur du bitcoin",
              "Oui, on peut copier des bitcoins aussi facilement que l'on peut copier des photos numériques",
              "Oui, mais copier des bitcoins nécessite des ordinateurs spécialisés",
            ],
            feedback: [
              "C'est tout à fait juste!",
              "Tu sais que ce n'est pas vrai. Essaie de nouveau.",
              "Faux. Il n'y a aucune façon de copier ou dupliquer des bitcoins.",
            ],
            id: "copyBitcoin",
            question: "Si le Bitcoin est une monnaie numérique, est-ce que quelqu'un pourrait le copier et ainsi créer de l'argent gratuit?",
            text: "La valeur d'un bitcoin ne peut jamais être copié. C'est justement pour cela que le Bitcoin est une invention aussi puissante!!\n\n La plupart des fichiers numériques, comme les photo d'un iPhone, une chanson en format MP3, ou un document Microsoft Word, peuvent facilement être dupliqués et partagés. \n\n Le logiciel Bitcoin empêche la duplication, ou dans le jargon bitcoin “la double dépense”, de la monnaie numérique. On va expliquer le fonctionnement précis de l'algorithme plus tard!",
            title: "Si le Bitcoin est une monnaie numérique, est-ce que quelqu'un pourrait le copier et ainsi créer de l'argent gratuit?",
            type: "Text",
          },
        ],
        meta: {
          id: "bitcoinWhatIsIt",
          title: "Bitcoin: Qu'est-ce que c'est?",
        },
      },
      {
        content: [
          {
            answers: [
              "Parce que les gens ont confiance que d'autres personnes vont évaluer la monnaie de façon similaire",
              "Parce que votre mère vous l'a dit",
              "Parce qu'un billet d'un dollar vaut son poids en or",
            ],
            feedback: [
              "Exact. C'est ce qui permet à la monnaie de fonctionner!",
              "Elle l'a peut être fait. Mais ce n'est pas la bonne réponse ici!",
              "Non, plus maintenant. Dans le passé, on pouvait échanger des dollars contre de l'or, mais ce n'est plus le cas.",
            ],
            id: "moneySocialAggrement",
            question: "Pourquoi les monnaies ont de la valeur?",
            text: "La monnaie nécessite la confiance du peuple.\n\n Les gens font confiance à la monnaie papier dans leurs poches. Ils font confiance aux chiffres dans leurs comptes banquaires en ligne. Ils font confiance que le solde de leurs cartes cadeaux sera disponible pour des transactions. \n\n Avoir de la monnaie permet au gens de l'échanger facilement pour des biens ou des services.",
            title: "L'argent est un contrat social.",
            type: "Text",
          },
          {
            answers: [
              "La double coïncidence des besoins",
              "La coïncidence du jour et de la nuit",
              "La coïncidence de la lune bloquant la lumière du Soleil",
            ],
            feedback: [
              "Exact. La monnaie permet des transactions qui ne nécessite par de négotiation sur la forme du paiement.",
              "Il ne faut pas cliquer sur n'importe quoi voyons...",
              "Et non, on appelle cette coïncidence une éclipse solaire 🌚 et la monnaie ne change rien dans ce cas.",
            ],
            id: "coincidenceOfWants",
            question: "Quelle coïncidence est évitée par l'utilisation de la monnaie?",
            text: "Il y a des siècles, avant l'invention de la monnaie, les gens faisaient du troc -- c'est-à-dire ils négotiaient l'échange d'un bien contre un autre type de bien ou de service. \n\n Disons que vous vouliez mangez dans un restaurant et que vous offriez au propriétaire un balais en échange d'un repas. Le propriétaire pouvait dire “non, mais je vais prendre trois chapeaux, si vous en avez”. \n\n Vous pouvez imaginer comme un système de troc pouvait être difficile et inefficace!\n\n En contrast, avec de la monnaie, un simple billet de 20$ règle cette transaction en sachant que le propriétaire du restaurant l'acceptera volontier.",
            title: "La monnaie permet d'éviter la “double coïncidence des besoins”...  C'est quoi ça??",
            type: "Text",
          },
          {
            answers: [
              "Des pierres, des coquillages et de l'or",
              "Des petites maisons de Monopoly en plastique",
              "Des pièces en chocolat",
            ],
            feedback: [
              "Exact. Des objets rares et difficiles à copier étaient souvent utilisés comme monnaie.",
              "Faux. Ils ont de la valeur lorsque l'on joue au jeu, mais pas dans le monde réel!",
              "Non. Ils sont délicieux, mais ils ne seraient pas utile comme monnaie.",
            ],
            id: "moneyEvolution",
            question: "Historiquement, quels objets ont déjà été utilisés comme monnaie?",
            text: "Thousands of years ago, society in Micronesia used very large and scarce stones as a form of agreed currency. \n\nStarting in the 1500’s, rare Cowrie shells (found in the ocean) became commonly used in many nations as a form of money.\n\nAnd for millenia, gold has been used as a form of money for countries around the world -- including the United States (until 1971).",
            title: "La monnaie a évoluée depuis le début de la civilisation.",
            type: "Text",
          },
          {
            answers: [
              "Parce qu'ils ont des caractéristiques essentielles, comme une bonne durabilité, une uniformité et qu'ils sont divisibles.",
              "Parce qu'ils brillent et qu'ils sont jolies.",
              "Parce qu'ils peuvent être transporter dans nos poches.",
            ],
            feedback: [
              "Exact. D'autres caractéristiques essentielles sont qu'ils sont rares et portables.",
              "Faux. C'est peut-être le cas, mais ce ne sont pas des caractéristiques utiles pour de la monnaie.",
              "Pas tout à fait. Bien que c'est objets étaient portable, ce n'est pas une raison suffisante en soi.",
            ],
            id: "whyStonesShellGold",
            question: "Pourquoi les pierres, les coquillages et l'or furent utilisés comme monnaie?",
            text: "Ces objets possèdent des caractéristiques essentielles, mais pas tous, pour une bonne monnaie. \n\n Quelles sont les caractéristiques essentielles pour une “bonne” monnaie? \n Rareté: peu abondante et difficile à reproduire ou copier \n Elle doit être acceptée: c'est relativement facile de vérifier son authenticité \n Durabilité: facile à maintenir, sans qu'elle périsse ou tombe en pièces \n Uniformité: facilement échangeable avec un autre objet du même type \n Portabilité: facile à transporter \n Divisible: peut-être séparer en pièces plus petites.",
            title: "Pourquoi les pierres, les coquillages et l'or furent utilisés comme monnaie?",
            type: "Text",
          },
          {
            answers: [
              "La monnaie permet d'acheter des biens et des services aujourd'hui et demain.",
              "La monnaie permet de se rendre sur la Lune.",
              "La monnaie est la solution de tous les problèmes.",
            ],
            feedback: [
              "C'est tout à fait cela!",
              "Faux. Bien que cela puisse changer dans le futur ;)",
              "Pas tout à fait. Bien que des gens le croient, cette réponse n'identifie pas la raison d'être principale de la monnaie.",
            ],
            id: "moneyIsImportant",
            question: "Quelle est la raison d'être principale de la monnaie? Pourquoi est-elle importante?",
            text: "Tout le monde sait que la monnaie est importante. \n\n La plupart des gens échangent leur temps et leur énergie, sous la forme de travail, pour obtenir de la monnaie. Ils le font pour pouvoir acheter des biens et des servies aujourd'hui et dans le futur.",
            title: "La monnaie est importante pour les individus",
            type: "Text",
          },
          {
            answers: [
              "La banque centrale du pays, par exemple la Banque Centrale des États-Unis (La Réserve Fédérale)",
              "Mr Burns de la série télévisée Les Simpson",
              "Un gars avec une imprimante dans son sous-sol",
            ],
            feedback: [
              "Exact. Le gouvernement peut imprimer autant de monnaie qu'il veut, quand il veut.",
              "Faux. Bien que dans la série, il ne manque presque jamais d'argent.",
              "Non. Certaines personnes peuvent imprimer des faux billets, mais ce n'est définitivement pas légal!",
            ],
            id: "moneyImportantGovernement",
            question: "Qui peut imprimer de la monnaie quand ils le veulent?",
            text: "Les économies modernes sont organisées par les nations: USA, Japon, Suisse, Brésil, Norvège, Chine, etc. \n\n Ainsi, dans la majorité des nations, le gouvernement détient le pouvoir de créer et de contrôler la monnaie. \n\n Aux États-Unis, la Banque Centrale (appelée la Réserve Fédérale, ou “Fed”) peut imprimer ou créer plus de Dollars US quand elle le désire. \n\n La “Fed” ne requière pas la permission du Président, ni du Congrès, et certainement pas des citoyens. \n\n Imaginez si vous pouviez imprimer des Dollars US quand vous le vouliez, que feriez-vous??",
            title: "La monnaie est aussi importante pour les gouvernements",
            type: "Text",
          },
        ],
        meta: {
          id: "WhatIsMoney",
          title: "Qu'est-ce que c'est de la monnaie? ",
        },
      },
      {
        content: [
          {
            answers: [
              "Elle est créée sous les ordres du gouvernement national du pays.",
              "Par le gérant d'une banque locale.",
              "Par le créateur du jeu Monopoly.",
            ],
            feedback: [
              "Exact. La banque centrale d'un gouvernement crée la monnaie fiat.",
              "Faux. Une banque locale ne peut que gérer de la monnaie qui a été créée précédemment par le gouvernement.",
              "Non. Essayez encore!",
            ],
            id: "WhatIsFiat",
            question: "Qui crée l'argent fiat, comme le Dollar US ou Canadien?",
            text: "Toutes les monnaies nationales en circulation aujourd'hui sont appelées monnaie fiat. Ceci inclus le Dollars US, le Yen Japonais, le Franc Suisse, le Dollar Canadien et ainsi de suite. \n\n Le mot “fiat” provient du Latin, il signifie “par décret”, c'est-à-dire “par ordre officielle”. \n\n Ceci signifie que toute monnaie fiat, incluant le Dollar US, est simplement créée sous les ordres du gouvernement national.",
            title: "La monnaie fiat: qu'est-ce que c'est?",
            type: "Text",
          },
          {
            answers: [
              "Tous les gouvernements abusent éventuellement de leur pouvoir sur leurs monnaies fiat.",
              "Les banques locales peuvent manquer d'espace dans leur coffres pour stoquer tous les billets.",
              "On pourrait manquer d'arbres pour fabriquer tous ces billets en papier additionnels.",
            ],
            feedback: [
              "Exact. Historiquement, les gouvernements n'ont pas pu résister à la tentation d'imprimer plus de monnaie puisqu'ils n'ont pas d'obligation de repayer cette nouvelle monnaie.",
              "Non, c'est certainement pas le cas.",
              "Faux. D'ailleur plusieurs billets ne sont pas fait à partir des arbres. Essayez encore.",
            ],
            id: "whyCareAboutFiatMoney",
            question: "Pourquoi devrais-je me soucier du contrôle du gouvernement sur la monnaie fiat?",
            text: "Tel que vu dans un quiz précédent, la banque centrale des États-Unis est la Réserve Fédérale, ou la “Fed”.\n\n La Fed peut imprimer plus de monnaie quand elle le désire et elle ne requiert pas la permission du Président, ni du Congrès et certainement pas des citoyens. \n\n Avec ce genre de contrôle sur la monnaie, il peut être très tentant pour ces authorités d'en abuser. Cela mène parfois à de l'inflation massive, des confiscations arbitraires et de la corruption. \n\n En fait, Alan Greenspan, le célèbre ex-président de la The Fed, a déclaré que les États-Unis “peut payer n'importe quelle dette, puisque l'on peut toujours imprimer plus de billets pour faire cela”.",
            title: "Je fais confiance à mon gouvernement. \n Pourquoi je devrais me soucier de la monnaie fiat?",
            type: "Text",
          },
          {
            answers: [
              "La création de monnaie supplémentaire cause de l'inflation.",
              "Les gens doivent échanger leur anciens billets de bank à chaque année.",
              "L'apparence des billets change.",
            ],
            feedback: [
              "Exact. Ceci signifie que les biens et les services vont être plus dispendieux à l'avenir.",
              "Non. Les vieux billets sont aussi valides que les nouveaux.",
              "Faux. Bien que le gouvernement peut change l'apparence des billets, ceci n'a rien à voir avec l'accroissement des réserves monétaires.",
            ],
            id: "GovernementCanPrintMoney",
            question: "Quel impact aura l'impression de monnaie par le gouvernement?",
            text: "Tout le monde devrait s'en soucier! \n\n L'impression de monnaie par le gouvernement, ou plutôt l'accroissement de la réserve monétaire, cause de l'inflation. \n\n L'inflation est un accroissement du prix des biens et des services. En d'autre mots, le prix d'un objet sera plus dispendieux à l'avenir que maintenant. \n\n Alors que signifie l'inflation pour les citoyens? \n\n Au Royaume-Uni, la Livre Sterling  a perdu 99.5% de sa valeur depuis sont introduction il y a plus de 300 ans. \n\n Aux Etats-Unis, le dollar a perdu 97% de sa valeur depuis la fin de la Deuxième Guerre Mondiale, il y a environ 100 ans. \n\n Cela signifie qu'un bifteck qui coûtait $0.30 en 1920... était $3 en 1990… et est environ $15 aujourd'hui, en l'an 2020!",
            title: "Qui devrait se soucier que le gouvernement peut imprimer de la monnaie sans limite?",
            type: "Text",
          },
          {
            answers: [
              "Toutes les monnaies fiat ont perdu une quantité massive de valeur.",
              "La valeur reste la même pour toujours.",
              "L'apparence et la forme des billets papier change à tous les 10 ans environ.",
            ],
            feedback: [
              "Exact. Ceci est vrai même pour le USD, qui a perdu 97% de sa valeur dans le dernier 100 ans.",
              "Faux. Essayez de nouveau.",
              "Pas tout à fait. Bien que l'apparence et la forme des billets peuvent changer, ceci n'a aucun impacte sur leur valeur.",
            ],
            id: "FiatLosesValueOverTime",
            question: "Qu'arrive-t-il à la valeur des monnaies fiat avec le temps?",
            text: "C'est le cas. \n\n A travers l'histoire, il y a eu 775 monnaies fiat qui ont été créées. La plupart n'existe plus et l'espérance de vie d'une nouvelle monnaie fiat est de seulement 27 ans. \n\n La livre Sterling est la plus vieille monnaie fiat du monde. Elle a perdu plus de 99% de sa valeur depuis 1694. \n\n Il n'y a aucun exemple de monnaie fiat ayant conservé sa valeur. Ceci est l'inflation. \n C'Est une forme de vol de votre argent durement gagner!",
            title: "Est-ce que cela signifie que toutes les monnaies fiat perdent de la valeur avec le temps?",
            type: "Text",
          },
          {
            answers: [
              "La monnaie est difficile a bouger autour du monde et elle peut être surveillée.",
              "On a plus besoin de monnaie au 21ième siècle.",
              "L'argent est la source de tous les maux.",
            ],
            feedback: [
              "Exact. On va expliquer plus de détails concernant ces enjeux dans un prochain quiz. Continuez de creuser!!",
              "Faux. Vous savez que ce n'est pas la cas.",
              "Bien que plusieurs personnes peuvent y croire, ce n'est pas la réponse que l'on cherche.",
            ],
            id: "OtherIssues",
            question: "Quels autres enjeux est associés avec les monnaies fiat?",
            text: "Oui, il y a plusieurs autres enjeux avec les monnaies fiat modernes. \n\n Premièrement, il peut être extrêmement difficile de déplacer de la monnaie dans le monde. Souvent, les gouvernements vont mettre des restrictions sur ces déplacements, et parfois, ils vont même confisquer les fonds sans justifications valides. Même quand on réussit a envoyer de l'argent, des frais de transaction énormes rendent le déplacement dispendieux. \n\n Deuxièmement, même aux États-Unis, il y a eu une perte totale de discrétion puisque la majorité du commerce utilise des carte de débit ou de crédit, ainsi que des systèmes en ligne tel que PayPal et Apple Pay.\n\n Avez-vous remarqué que des publicités apparaissent sur vos média sociaux ou dans vos courriels quelques instants après que vous ayez fait une recherche sur un bien ou un service? On appelle ceci “l'économie de la surveillance”, et c'est basé sur la vente de vos données financières.",
            title: "D'accord, les monnaie fiat perdent de la valeur avec le temps. Y-a-t-il d'autres problèmes?",
            type: "Text",
          },
        ],
        meta: {
          id: "HowDoesMoneyWork",
          title: "Comment fonctionne la monnaie? ",
        },
      },
      {
        content: [
          {
            answers: [
              "Oui. On ne pourra jamais créer plus de 21 millions de bitcoins.",
              "Non. Le gouvernement peut créer plus de bitcoin quand il le veut.",
              "Non, le logiciel bitcoin peut être changé pour permettre la création de plus de bitcoins.",
            ],
            feedback: [
              "Exacte. En limitant la quantité qui peut être créée, le Bitcoin a été conçu pour accroître sa valeur avec le temps.",
              "Faux. Le gouvernement n'a aucun contrôle sur le Bitcoin.",
              "Faux. Une des caractéristiques clées du bitcoin est que la réserve est limitée pour toujours.",
            ],
            id: "LimitedSupply",
            question: "Est-ce que la réserve de bitcoin limitée pour toujours?",
            text: "Les gouvernement peuvent imprimer de la monnaie fiat en quantités illimitées. \n\n Contrairement à cela, la réserve maximale de Bitcoin est fixée et elle ne peut jamais dépasser 21 millions de bitcoins. \n\n Un accroissement continuel de la réserve de monnaie fiat cause de l'inflation. Ceci signifie que l'argent que vous avez aujourd'hui aura une valeur moindre dans le futur. \n\n Un exemple simple de ceci: \n Une miche de pain qui valait environ 8 cents en 1920, valait environ $1.00 en 1990 et aujourd'hui il vaut environ $2.50 ! \n\n La réserve limitée de bitcoin a l'effet inverse, une de déflation. \n\n Ceci signifie que le bitcoin que vous détenez aujourd'hui est conçu pour avoir plus de valeur dans le futur, parce qu'il est rare.",
            title: "Caractéristique spéciale #1:\n Une réserve limitée",
            type: "Text",
          },
          {
            answers: [
              "Non.  Le Bitcoin est complètement “décentralisé”.",
              "Oui. Il est contrôlé par les Nations Unis.",
              "Oui. Il est contrôlé par les plus grandes banques du monde.",
            ],
            feedback: [
              "Exact. Il n'y a pas de compagnie, de gouvernement ou d'institution qui contrôle le bitcoin. N'importe qui peut utiliser le bitcoin et tout ce qu'il faut c'est un téléphone intelligent et une connection à internet.",
              "Faux. Essayez de nouveau.",
              "Faux, mais vous le saviez déjà!",
            ],
            id: "Decentralized",
            question: "Est-ce que le bitcoin est centralisé?",
            text: "La monnaie fiat est contrôlée par les banques et les gouvernements, c'est pour cela que l'on dit qu'elle est centralisée. \n\n Le Bitcoin n'est pas contrôlé par une personne, un gouvernement ou une compagnie, se qui signifie qu'il est décentralisé. \n\n Puisque personne ne contrôle le bitcoin, cela signifie que personne ne peut vous limiter son accès, pour des raisons de race, de genre, de votre revenu, de votre cote de crédit, votre position géographique ou n'importe quel autre facteur. \n\n N'importe qui, n'importe ou dans le monde, peut accéder et utiliser le Bitcoin quand il le veut. Tout ce qui est nécessaire est un ordinateur ou un téléphone intelligent et une connection internet!",
            title: "Caracteristique spéciale #2: Décentralisation",
            type: "Text",
          },
          {
            answers: [
              "Non. Il est impossible de faire des contrefaçons de Bitcoin.",
              "Oui. Sauf que la création de faux bitcoin nécessite des ordinateurs très spécialisés.",
              "Oui. Le gouvernement peut imprimer autant de bitcoins qu'il le souhaite.",
            ],
            feedback: [
              "Ceci est la bonne réponse. Dans un prochain quiz, “Honey Badger” vous expliquera pourquoi c'est ainsi!",
              "Faux. Il n'y a aucune façon de copier ou dupliquer la valeur du bitcoin.",
              "Faux. Bien que le gouvernement peut imprimer une quantité illimité de dollars, il ne peut pas imprimer de bitcoin.",
            ],
            id: "NoCounterfeitMoney",
            question: "Est-ce que l'on peut créer des contrefaçons de Bitcoin?",
            text: "La monnaie papier, les chèques et les transactions par carte de crédit peuvent tous être contrefait ou frauduleux. \n\n Le logiciel unique sur lequel repose le réseau Bitcoin élimine toute possibilité de duplication, y compris pour faire des contrefaçons. \n\n Les nouveaux bitcoin peuvent seulement être créé s'il y a un consensus parmis les participants du réseau, c'est-à-dire les gens qui roulent le logiciel bitcoin sur leurs ordinateurs ou téléphone intelligent. \n\n Ceci rend impossible la création de contrefaçons ou de faux bitcoins.",
            title: "Caractéristique spéciale #3: \nPas de contrefaçon",
            type: "Text",
          },
          {
            answers: [
              "0.00000001 BTC",
              "Un bitcoin entier. Il est impossible d'utiliser moins de un bitcoin.",
              "0.01 BTC",
            ],
            feedback: [
              "Yes. You can divide a bitcoin into 100,000,000 pieces. As you already know, the smallest unit of bitcoin — B0.00000001 — is known as a “sat”.",
              "Wrong. Bitcoin is highly divisible. You can easily use a very small fraction of a bitcoin.",
              "Incorrect. Although the smallest unit of US currency is one penny, a bitcoin is divisible by much more than 100x.",
            ],
            id: "HighlyDivisible",
            question: "What is the smallest amount of Bitcoin one can own, or use?",
            text: 'Old-fashioned fiat money can only be spent in amounts as small as one penny — or two decimal places for one US Dollar ($0.01).\n\nOn the other hand, Bitcoin can be divided 100,000,000 times over. This means that you could spend as little as ₿0.00000001. You will note the "₿" symbol, which is the Bitcoin equivalent of "$". Sometimes you will also see the use of BTC, instead of ₿.\n\nBy way of contrast, Bitcoin can handle very small payments — even those less than one US penny!',
            title: "Special Characteristic #4: \nHighly Divisible",
            type: "Text",
          },
          {
            answers: [
              "Yes. The bitcoin network is very secure.",
              "Maybe. It depends on the day of the week.",
              "No. It is open source software, and is easily attacked.",
            ],
            feedback: [
              "Correct. In fact, the Bitcoin network has never once been hacked. Answer the next question to learn more!",
              "Nice try, but wrong. The bitcoin network is safe and secure — 24 hours a day, 365 days a year.",
              "Icorrect. Although bitcoin is indeed “open source” software — or available to the public for free — is still extremely secure.",
            ],
            id: "securePartOne",
            question: "Is the Bitcoin network secure?",
            text: "The bitcoin network is worth well over $100 billion today. Accordingly, the network must be very secure — so that money is never stolen. \n\nBitcoin is known as the world’s first cryptocurrency. \n\nThe “crypto” part of the name comes from cryptography. Simply put, cryptography protects information through very complex math functions. \n\nMost people do not realize — but Bitcoin is actually the most secure computer network in the world ! \n\n(you may have heard about bitcoin “hacks” — which we will debunk in the next quiz)",
            title: "Special Characteristic #5: \nSecure -- Part I",
            type: "Text",
          },
          {
            answers: [
              "No. Bitcoin has never been hacked.",
              "Yes. Bitcoin gets hacked frequently.",
              "Yes. Bitcoin usually gets hacked on holidays, when traditional banks are closed.",
            ],
            feedback: [
              "That is correct. The bitcoin network has never been compromised. However, it is important to use only secure digital wallets to keep your personal bitcoins safe at all times.",
              "Wrong. Please try again.",
              "No silly, you know that is not the correct answer.",
            ],
            id: "securePartTwo",
            question: "Has Bitcoin ever been hacked?",
            text: "To be direct: the bitcoin network itself has never been hacked. Never once.\n\nThen what exactly has been hacked? \n\nCertain digital wallets that did not have proper security in place. \n\nJust like a physical wallet holds fiat currency (in the form of paper bills), digital wallets hold some amount of bitcoin. \n\nIn the physical world, criminals rob banks — and walk away with US Dollars. The fact that someone robbed a bank does not have any relationship as to whether the US Dollar is stable or reliable money. \n\nSimilarly, some computer hackers have stolen bitcoin from insecure digital wallets — the online equivalent of a bank robbery. \n\nHowever, it is important to know that the bitcoin network has never been hacked or compromised !",
            title: "Special Characteristic #5: \nSecure -- Part II",
            type: "Text",
          },
        ],
        meta: {
          id: "BitcoinWhySpecial",
          title: "Bitcoin: Why is it special? ",
        },
      },
    ],
    finishText: "That's all for now, we'll let you know when there's more to unearth",
    getRewardNow: "Answer quiz",
    keepDigging: "Keep digging!",
    phoneNumberNeeded: "Phone number required",
    quizComplete: "Quiz completed and {{amount}} sats earned",
    reviewQuiz: "Review quiz",
    satAccumulated: "Sats accumulated",
    satsEarned: {
      one: "1 sat earned",
      other: "{{formatted_number}} sats earned",
    },
    sectionsCompleted: "You've completed",
    title: "Earn",
    unlockQuestion: "To unlock, answer the question:",
    youEarned: "You Earned",
  },
  GetStartedScreen: {
    getStarted: "Get Started",
    headline: "Wallet powered by Galoy",
  },
  MapScreen: {
    locationPermissionMessage: "Activate your location so you know where you are on the map",
    locationPermissionNegative: "Cancel",
    locationPermissionNeutral: "Ask Me Later",
    locationPermissionPositive: "OK",
    locationPermissionTitle: "Locate yourself on the map",
    payBusiness: "pay this business",
    title: "Map",
  },
  ModalClipboard: {
    dismiss: "Dismiss",
    open: "Open",
    pendingBitcoin: "You have a Bitcoin address in your clipboard",
    pendingInvoice: "You have a Lightning Invoice in your clipboard",
  },
  MoveMoneyScreen: {
    receive: "Receive",
    send: "Send",
    title: "Home",
    updateAvailable: "An update is available.\nTab to update now",
    useLightning: "We use the Lightning Network.",
  },
  Overlay: {
    accounts: "Start by getting\nsome rewards!",
    rewards: {
      download: "We gave you 1 sat as a gift\nto download the app.",
      getMore: "Learn about #bitcoin and earn more!",
    },
  },
  PinScreen: {
    attemptsRemaining: "Incorrect PIN. %{attemptsRemaining} attempts remaining.",
    oneAttemptRemaining: "Incorrect PIN. 1 attempt remaining.",
    setPin: "Set your PIN code",
    setPinFailedMatch: "Pins didn't match - Set your PIN code",
    storePinFailed: "Unable to store your pin.",
    tooManyAttempts: "Too many failed attempts. Logging out.",
    verifyPin: "Verify your PIN code",
  },
  PriceScreen: {
    oneDay: "1D",
    oneMonth: "1M",
    oneWeek: "1W",
    oneYear: "1Y",
    prevMonths: "Previous months",
    satPrice: "Price for 100,000 sats: ",
    thisMonth: "This month",
    thisWeek: "This week",
    thisYear: "This year",
    today: "Today",
    yesterday: "Yesterday",
  },
  PrimaryScreen: {
    title: "Home",
  },
  ReceiveBitcoinScreen: {
    activateNotifications: "Do you want to activate notifications to be notified when the payment has arrived?",
    copyClipboard: "Invoice has been copied in the clipboard",
    copyClipboardBitcoin: "Bitcoin address has been copied in the clipboard",
    invoicePaid: "This invoice has been paid",
    setNote: "set a note",
    tapQrCodeCopy: "Tap QR Code to Copy",
    title: "Receive Bitcoin",
    error: "Failed to generate invoice. Please contact support if this problem persists.",
    copyInvoice: "Copy Invoice",
    shareInvoice: "Share Invoice",
    addAmount: "Request Specific Amount"
  },
  ScanningQRCodeScreen: {
    invalidContent: "We found:\n\n{{found}}\n\nThis is not a valid Bitcoin address or Lightning invoice",
    invalidTitle: "Invalid QR Code",
    noQrCode: "We could not find a QR code in the image",
    title: "Scan QR Code",
    invalidContentLnurl: "We found:\n\n{{found}}\n\n is not currently supported",
  },
  SecurityScreen: {
    biometricDescription: "Unlock with fingerprint or facial recognition.",
    biometricSubtitle: "Enable biometric authentication",
    biometricTitle: "Biometric",
    biometryNotAvailable: "Biometric sensor is not available.",
    biometryNotEnrolled: "Please register at least one biometric sensor in order to use biometric based authentication.",
    hideBalanceDescription: "Hides your balance on the home screen by default, so you don't reveal it to anyone looking at your screen.",
    hideBalanceSubtitle: "Hide balance",
    hideBalanceTitle: "Balance",
    pinDescription: "PIN is used as the backup authentication method for biometric authentication.",
    pinSubtitle: "Enable PIN",
    pinTitle: "PIN Code",
    setPin: "Set PIN",
  },
  SendBitcoinConfirmationScreen: {
    amountLabel: "Amount:",
    confirmPayment: "Confirm payment",
    confirmPaymentQuestion: "Do you want to confirm this payment?",
    destinationLabel: "To:",
    feeLabel: "Fee",
    memoLabel: "Note:",
    paymentFinal: "Payments are final.",
    stalePrice: "Your bitcoin price is old and was last updated {{timePeriod}} ago. Please restart the app before making a payment.",
    title: "Confirm Payment",
    totalLabel: "Total:",
    totalExceed: "Total exceeds your balance of {{balance}}",
  },
  SendBitcoinScreen: {
    amount: "Amount",
    amountExceed: "Amount exceeds your balance of {{balance}}",
    amountIsRequired: "Amount is required",
    cost: "Cost",
    destination: "Destination",
    destinationIsRequired: "Destination is required",
    fee: "network fee",
    feeCalculationUnsuccessful: "Calculation unsuccessful ⚠️",
    input: "Username, Lightning or BTC Address",
    invalidUsername: "Invalid username",
    noAmount: "This invoice doesn't have an amount, so you need to manually specify how much money you want to send",
    notConfirmed: "Payment has been sent\nbut is not confirmed yet\n\nYou can check the status\nof the payment in Transactions",
    note: "optional note",
    success: "Payment has been sent successfully",
    title: "Send Bitcoin",
    usernameNotFound: "A user matching the entered username could not be found.",
  },
  SettingsScreen: {
    activated: "Activated",
    tapLogIn: "Tap to log in",
    tapUserName: "Tap to set username",
    title: "Settings",
    csvTransactionsError: "Unable to export transactions to csv. Something went wrong. If issue persists please contact support.",
    lnurlNoUsername: "To generate an lnurl address you must first set a username.  Do you want to set a username now?",
    copyClipboardLnurl: "Lnurl address has been copied in the clipboard",
  },
  Languages: {
    "DEFAULT": "Default (OS)",
    "en": "English",
    "en-US": "English",
    "es": "Spanish",
    "es-SV": "Spanish",
    "pt-BR": "Portuguese",
  },
  SplashScreen: {
    update: "Your app is outdated. An update is needed before the app can be used.\n\nThis can be done from the PlayStore for Android and Testflight for iOS",
  },
  TransactionDetailScreen: {
    detail: "Transaction Details",
    paid: "Paid to/from",
    received: "You received",
    spent: "You spent",
  },
  TransactionScreen: {
    noTransaction: "No transaction to show",
    title: "Transactions",
    transactionHistoryTitle: "Transaction History",
  },
  TransferScreen: {
    title: "Transfer",
    percentageToConvert: "% to convert",
  },
  UsernameScreen: {
    "3CharactersMinimum": "at least 3 characters are necessary",
    "50CharactersMaximum": "Username cannot be longer than 50 characters",
    "available": "✅  %{input} is available",
    "confirmSubtext": "The username is permanent and can not be changed later",
    "confirmTitle": "Set %{input} as your username?",
    "forbiddenStart": "Cannot start with lnbc1, bc1, 1, or 3 and cannot be a Bitcoin address or Lightning invoice",
    "letterAndNumber": "Only lowercase letter, number and underscore (_) are accepted",
    "emailAddress": "Username must not be email address",
    "notAvailable": "❌  %{input} is not available",
    "success": "%{input} is now your username!",
    "usernameToUse": "What username do you want to use?",
  },
  WelcomeFirstScreen: {
    bank: "Bitcoin is designed to let you store, send and receive money, without relying on a bank or credit card.",
    before: "Before Bitcoin, people had to rely on banks or credit card providers, to spend, send and receive money.",
    care: "Why should I care?",
    learn: "I don't mean to badger you, but there's lot more to learn, dig in...",
    learnToEarn: "Learn to Earn",
  },
  WelcomePhoneInputScreen: {
    header: "Enter your phone number, and we'll text you an access code.",
    headerVerify: "Verify you are human",
    placeholder: "Phone Number",
    verify: "Click to Verify",
    continue: "Continue",
  },
  WelcomePhoneValidationScreen: {
    errorLoggingIn: "Error logging in. Did you use the right code?",
    header: "To confirm your phone number, enter the code we just sent you on %{phone}",
    need6Digits: "The code needs to have 6 digits",
    placeholder: "6 Digit Code",
    sendAgain: "Send Again",
  },
  common: {
    activateWallet: "Activate Wallet",
    amountRequired: "Amount is required",
    back: "Back",
    bank: "Bank",
    bankAccount: "Cash Account",
    bitcoin: "Bitcoin",
    bitcoinPrice: "Bitcoin Price",
    cancel: "Cancel",
    close: "Close",
    confirm: "Confirm",
    csvExport: "Export transactions as CSV",
    date: "Date",
    description: "Description",
    domain: "Domain",
    email: "Email",
    error: "Error",
    fatal: "Fatal",
    fee: "fee",
    Fee: "Fee",
    fees: "Fees",
    feeSats: "Fees (sats)",
    feesUsd: "Fees (USD)",
    firstName: "First Name",
    from: "From",
    hour: "hour",
    hours: "hours",
    invoice: "Invoice",
    language: "Language",
    languagePreference: "Language preference",
    lastName: "Last Name",
    later: "Later",
    loggedOut: "You have been logged out.",
    logout: "Log Out",
    minutes: "minutes",
    needWallet: "Validate your phone to open your wallet",
    next: "Next",
    No: "No",
    note: "Note",
    notification: "Notification",
    ok: "OK",
    openWallet: "Open Wallet",
    phoneNumber: "Phone Number",
    reauth: "Your session has expired. Please log in again.",
    restart: "Restart",
    sats: "sats",
    search: "Search",
    security: "Security",
    send: "Send",
    setAnAmount: "set an amount",
    share: "Share",
    shareBitcoin: "Share Bitcoin Address",
    shareLightning: "Share Lightning Invoice",
    soon: "Coming soon!",
    success: "Success!",
    to: "To",
    Total: "Total",
    transactions: "Transactions",
    transactionsError: "Error loading transactions",
    tryAgain: "Try Again",
    type: "Type",
    username: "Username",
    usernameRequired: "Username is required",
    yes: "Yes",
  },
  errors: {
    generic: "There was an error.\nPlease try again later.",
    invalidEmail: "Invalid email",
    invalidPhoneNumber: "is not a valid phone number",
    tooManyRequestsPhoneCode: "Too many requests. Please wait before requesting another text message.",
    network: {
      server: "Server Error. Please try again later",
      request: "Request issue.\nContact support if the problem persists",
      connection: "Connection issue.\nVerify your internet connection",
    },
    unexpectedError: "Unexpected error occurred",
    restartApp: "Please restart the application.",
    problemPersists: "If problem persists contact support.",
    fatalError: "Sorry we appear to be having issues loading the application data.  If problems persist please contact support.",
    showError: "Show Error",
  },
  notifications: {
    payment: {
      body: "You just received ${{value}} sats",
      title: "Payment received",
    },
  },
  tippingLink: {
    title: "Want to receive tips? Share your tipping link!",
    copied: "{{data}} saved to clipboard",
  },
  whatsapp: {
    contactUs: "Need help? Talk to us on WhatsApp!",
    defaultSupportMessage: "Hey there! I need some help with Bitcoin Beach Wallet",
    contactSupport: "Contact Support",
  },
  lnurl: {
    overLimit: "You can't send more than max amount",
    underLimit: "You can't send less than min amount",
    commentRequired: "Comment required",
    viewPrintable: "View Printable Version",
  },
}
